databases:
  - name: seizure_tracker
    databaseName: seizure_tracker_production
    user: seizure_tracker
    plan: free

services:
  - type: web
    name: seizure_tracker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seizure_tracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 1 # sensible default